version: 2.0

jobs:
  build:
    docker:
      - image: makenowjust/techbookfest-build:0.26.1-4
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            bundle install --path=vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Build
          command: bundle exec rake -j
      - store_artifacts:
          path: build
      - run:
          name: Lint
          command: bundle exec rake lint
      - run:
          name: Test
          command: bundle exec rake test
      - persist_to_workspace:
          root: build
          paths:
            - docs
  deploy:
    docker:
      - image: makenowjust/techbookfest-build:0.26.1-4
    steps:
      - checkout
      - attach_workspace:
          at: build
      - add_ssh_keys:
          fingerprints:
            - "ad:ae:94:c4:a1:35:a3:9f:10:dd:ae:d7:ea:b6:89:1d"
      - run:
          name: Deploy
          command: |
            git config --global user.email 'make.just.on@gmail.com'
            git config --global user.name 'TSUYUSATO Kitsune (bot)'

            git clone $CIRCLE_REPOSITORY_URL build/out

            cd build/out
            git checkout gh-pages || git checkout --orphan gh-pages
            git rm -rf . || true
            cd ../..

            cp -a build/docs/. build/out/.

            mkdir -p build/out/.circleci && cp -a .circleci/. build/out/.circleci

            cd build/out
            git add -A
            git commit --allow-empty -m "Deploy: ${CIRCLE_SHA1}"
            GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa_adae94c4a135a39f10ddaed7eab6891d -F /dev/null"  git push origin gh-pages

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
